name: Build DotNet
author: Els_kom
description: 📦 GitHub action to build, test, and package projects.

inputs:
    SOLUTION_FILE_PATH:
        description: Filepath of the solution of which contains all the projects to be built, optionally tested and packed, relative to root of repository
        required: false
        default: ''
    RESTORE:
        description: Flag to toggle running restore for the projects about to be built, enabled by default
        required: false
        default: true
    TEST:
        description: Flag to toggle running unit tests for the projects built, disabled by default
        required: false
        default: false
    PACK:
        description: Flag to toggle packing the projects built
        required: false
        default: true
    PUSH:
        description: Flag to toggle pushing the packages to a nuget feed, disabled by default
        required: false
        default: false
    SOURCE_NAME:
        description: The source to use when pushing, nuget.org by default
        required: false
        default: nuget.org

runs:
    using: node16
    main: index.js

branding:
    icon: package
    color: blue
